### ISSUE TITLE
Documentation #1

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#90]

**Comment by thangixd** [comment]
We need to update our readme.md for e.g.

run python tracex/manage.py migrate to update the database and apply all changes stored in the migrations folder

give out:

![image](https://github.com/bptlab/TracEX/assets/105175491/b384d243-4c39-4dbc-adf6-fb882b6e8638)

since our root folder is now tracex_project instead of tracex

**Comment by tkv29** [comment]
Deploy django in docker and also add in readme so a user dont have to access the code

**Comment by tkv29** [comment]
add https://github.com/marketplace/actions/code-coverage-summary

**Comment by tkv29** [comment]
https://github.com/bptlab/ark_automate

**Comment by tkv29** [comment]
create and write articles in wiki how to use: https://github.com/bptlab/ark_automate/wiki

**Comment by tkv29** [comment]
in the end deploy a release 


![Image](https://github.com/bptlab/TracEX/assets/73845255/d931c7fe-bdeb-4d0d-ade4-9cf2105e723e)

**Comment by nils-schmitt** [comment]
We should add a detailed describtion how to install python and graphviz properly with the Path settings

**Comment by tkv29** [comment]
Pre-commit automatically sets a comma after the last input parameter. please look through the code and add it if its missing for consistency

![Image](https://github.com/bptlab/TracEX/assets/73845255/8dd4b21a-e5d5-4ed2-88af-55e7a5bc679b)
